// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package todos

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"
import "github.com/google/uuid"

func deleteIcon() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<image src=\"/assets/delete.svg\" class=\"delete-icon\" @click=\"await db.removeItem(id).then(console.log); active = false\"></image>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func textXData(id uuid.NullUUID) string {
	var uID uuid.UUID
	if id.Valid {
		uID = id.UUID
	} else {
		uID = uuid.New()
	}
	return fmt.Sprintf(`{
type : 'text',
id: '%v',
active : true,
title : '' ,
text : '',
async init(){
let data = await db.getItem('%v')
if (data){
this.title = data.title
this.text = data.text
}
},
}`, uID, uID)
}

func TextToDo(id uuid.NullUUID) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<section id=\"ajax-target\"><div class=\"todo-container grid grid-cols-3 grid-rows-1 \" x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(textXData(id))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/todos/ToDos.templ`, Line: 36, Col: 83}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" x-init=\"$watch('$data',data =>data.active && db.storeItem(data))\" x-show=\"active\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = deleteIcon().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<input class=\"p-small h2 col-span-1\" type=\"text\" placeholder=\"Title\" x-model=\"title\"> <textarea @change=\"text=$el.value\" class=\"p-small h3 col-span-2\" placeholder=\"Type your text here\" x-model=\"text\"></textarea></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func checklistXData(id uuid.NullUUID) string {
	var uID uuid.UUID
	if id.Valid {
		uID = id.UUID
	} else {
		uID = uuid.New()
	}
	return fmt.Sprintf(`{
type : 'checklist',
id: '%v',
title : '' ,
active : true,
list: [{title : '' , done : false , key : 0 }],
async init(){
let data = await db.getItem('%v')
if (data){
this.title = data.title
this.list = data.list
}
}
}`, uID, uID)
}

func CheckListToDo(id uuid.NullUUID) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<section id=\"ajax-target\"><div class=\"todo-container flex flex-row flex-wrap\" x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(checklistXData(id))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/todos/ToDos.templ`, Line: 71, Col: 83}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" x-init=\"$watch('$data',data => data.active && db.storeItem(data))\" x-show=\"active\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = deleteIcon().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<input class=\"p-smaller h2 col-span-1 w-full\" type=\"text\" placeholder=\"Title\" x-model=\"title\"><template x-for=\"(task , key) in list\"><div class=\"w-1/3 flex flex-row items-center\" x-effet=\"list[k]=task\"><input @change=\"task.title=$el.value\" type=\"text\" class=\"p-small h2\" x-init=\"$el.value=task.title\" placeholder=\"Task\"> <image @click=\"task.done=!task.done\" :src=\"task.done ? '/assets/done.svg' : '/assets/notdone.svg'\"></image> <image @click=\"list = list.filter(e=>e.k!==task.k)\" src=\"/assets/delete.svg\"></image></div></template><div class=\"w-1/3\" @click=\"list.push({title : '' , done : false, k : list.length })\"><h2 class=\"p-small\">New task</h2></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func imageXData(id uuid.NullUUID) string {
	var uID uuid.UUID
	if id.Valid {
		uID = id.UUID
	} else {
		uID = uuid.New()
	}
	return fmt.Sprintf(`{
type : 'image',
id: '%v',
title : '' ,
active : true,
base:'' ,
overlay: '',
async init(){
let data = await db.getItem('%v')
if (data){
this.title = data.title
this.base = data.base
this.overlay = data.overlay
}
}
}`, uID, uID)
}

func ImageToDo(id uuid.NullUUID) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<section id=\"ajax-target\"><div class=\"todo-container grid grid-cols-3 grid-rows-1\" x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(imageXData(id))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/todos/ToDos.templ`, Line: 118, Col: 83}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" x-init=\"$watch('$data', data => data.active && db.storeItem(data))\" x-show=\"active\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = deleteIcon().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<div class=\"col-span-1 p-small flex flex-col justify-around\"><input class=\"p-smaller h2\" type=\"text\" placeholder=\"Title\" x-model=\"title\"> <input class=\"p-smaller h2\" type=\"file\" accept=\"image/*\" @change=\"async () =>base = await fileToB64($el.files[0]) \"> <button class=\"button\" @click=\"overlay=''; clearCanvas(id) \">Clear</button> <input type=\"range\" min=\"1\" max=\"20\" step=\"1\" value=\"2\" name=\"linewidth\" x-ref=\"linewidth\" @change=\"setCanvasSettings(id,$el.value)\"> <label for=\"linewidth\">Linewidth </label> <input type=\"color\" name=\"color\" value=\"#000000\" @change=\"setCanvasSettings(id,null,$el.value)\"> <label for=\"color\">Color</label></div><div class=\"col-span-2 p-small\"><div class=\"drawing-area\"><image class=\"drawing-element\" style=\"z-index: 1;\" :src=\"base\"></image><canvas class=\"drawing-element\" style=\"z-index: 2;\" :id=\"id\" x-init=\" async ()=> {await init(); initCanvas(id , $data.overlay , (k)=>{overlay=k})}\"></canvas></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
